development:
  adapter: postgresql
  encoding: unicode
  database: otters_dev
  pool: 5
  username: otters

test:
  adapter: sqlite3
  database: test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: otters-site
  pool: 5
  username: otters-site
